//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBed.Services
{
    using System.CodeDom.Compiler;
    using System.Diagnostics;
    using System.ServiceModel;
    using System.ServiceModel.Channels;

    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName = "Services.ITimeService")]
    public interface ITimeService
    {
        #region Public Methods

        [OperationContract(Action = "http://tempuri.org/ITimeService/GetFormattedServerTime", 
            ReplyAction = "http://tempuri.org/ITimeService/GetFormattedServerTimeResponse")]
        string GetFormattedServerTime(string format);

        [OperationContract(Action = "http://tempuri.org/ITimeService/GetServerTime", ReplyAction = "http://tempuri.org/ITimeService/GetServerTimeResponse")]
        string GetServerTime();

        #endregion
    }

    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface ITimeServiceChannel : ITimeService, IClientChannel
    {
    }

    [DebuggerStepThrough]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public class TimeServiceClient : ClientBase<ITimeService>, ITimeService
    {
        #region Constructors and Destructors

        public TimeServiceClient()
        {
        }

        public TimeServiceClient(string endpointConfigurationName)
            : base(endpointConfigurationName)
        {
        }

        public TimeServiceClient(string endpointConfigurationName, string remoteAddress)
            : base(endpointConfigurationName, remoteAddress)
        {
        }

        public TimeServiceClient(string endpointConfigurationName, EndpointAddress remoteAddress)
            : base(endpointConfigurationName, remoteAddress)
        {
        }

        public TimeServiceClient(Binding binding, EndpointAddress remoteAddress)
            : base(binding, remoteAddress)
        {
        }

        #endregion

        #region Public Methods

        public string GetFormattedServerTime(string format)
        {
            return base.Channel.GetFormattedServerTime(format);
        }

        public string GetServerTime()
        {
            return base.Channel.GetServerTime();
        }

        #endregion
    }
}